remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Tiff Fehr
description: Online presence of Tiff Fehr, a data journalist and coder at The New York Times
google_analytics: G-RDFQSCYNP4
# logo: /assets/img/logo.png